version: "3"
services:
  mysql-container:
    image: mysql:8.0.32
    platform: linux/arm64
    networks:
      - project1-network
    volumes:
      - mysqlvol:/var/lib/mysql # MySQL 데이터 저장을 위한 볼륨 마운트
    restart: always # 컨테이너 재시작 설정
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: cloud_native
      MYSQL_USER: jeonghyeon
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  spring_server1:
    networks:
      - project1-network
    depends_on:
      - mysql-container
    image: toolkithi/my-spring:latest
    restart: always
    environment:
      DB_USERNAME: jeonghyeon
      DB_HOST: mysql-container
      DB_PASSWORD: password
      DB_NAME: cloud_native
      PORT: 8080
      DB_PORT: 3306
      SERVER_NUMBER: 1
      JWT_SECRET: dpoasjkopwkqop32j1p3oj21pjpsaojdsapojopdjsdsadsa81203podjas0809s09
  spring_server2:
    networks:
      - project1-network
    depends_on:
      - mysql-container
    image: toolkithi/my-spring:latest
    restart: always
    environment:
      DB_USERNAME: jeonghyeon
      DB_HOST: mysql-container
      DB_PASSWORD: password
      DB_NAME: cloud_native
      PORT: 8081
      DB_PORT: 3306
      SERVER_NUMBER: 2
      JWT_SECRET: dpoasjkopwkqop32j1p3oj21pjpsaojdsapojopdjsdsadsa81203podjas0809s09
  proxy:
    networks:
      - project1-network
    image: toolkithi/mynginx:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - spring_server1
networks:
  project1-network:
volumes:
  mysqlvol:
